# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    keycloak_url: '%env(KEYCLOAK_URL)%'
    keycloak_realm: '%env(KEYCLOAK_REALM)%'
    keycloak_client_id: '%env(KEYCLOAK_CLIENT_ID)%'
    meili_url: '%env(MEILI_URL)%'
    meili_master_key: '%env(MEILI_MASTER_KEY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true  # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Security\KeycloakAccessTokenHandler:
        arguments:
            $keycloakUrl: '%keycloak_url%'
            $keycloakRealm: '%keycloak_realm%'

    App\Search\MeilisearchClient:
        arguments:
            $meiliUrl: '%meili_url%'
            $masterKey: '%meili_master_key%'
