<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\SecretLinkRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Types\UuidType;
use Symfony\Component\Serializer\Attribute\Groups;
use Symfony\Component\Uid\Uuid;

/**
 * Secure Bridge — shareable one-shot secret link (E2E encrypted).
 *
 * The encryption key is a random 32-byte value generated by the client and
 * embedded in the URL fragment (e.g. /secret/{id}#<keyBase64>). Fragments
 * never leave the browser, so the server only ever sees opaque ciphertext.
 *
 * TTL is a hard 10 minutes; the link is also burned after the first
 * successful "consume" call.
 *
 *   - requireConfirmation=true (default): GET returns ciphertext without
 *     burning, and a separate POST /consume triggers the burn. This blocks
 *     email-preview bots from killing the link by just fetching the URL.
 *   - requireAuth=true: both GET and consume require a ROLE_USER token.
 *     Useful for extra-sensitive internal sharing.
 */
#[ORM\Entity(repositoryClass: SecretLinkRepository::class)]
#[ORM\Table(name: 'secret_link')]
#[ORM\HasLifecycleCallbacks]
class SecretLink
{
    public const TTL_SECONDS = 600; // 10 minutes

    #[ORM\Id]
    #[ORM\Column(type: UuidType::NAME, unique: true)]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\CustomIdGenerator(class: 'doctrine.uuid_generator')]
    #[Groups(['secret_link:read', 'secret_link:created'])]
    private ?Uuid $id = null;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(nullable: false)]
    private User $owner;

    /**
     * Base64(iv || ciphertext || tag) — AES-256-GCM envelope produced by the
     * client using an ephemeral random key carried in the URL fragment.
     */
    #[ORM\Column(type: Types::TEXT)]
    #[Groups(['secret_link:read'])]
    private string $ciphertext = '';

    #[ORM\Column(type: Types::BOOLEAN, options: ['default' => true])]
    #[Groups(['secret_link:read', 'secret_link:created'])]
    private bool $requireConfirmation = true;

    #[ORM\Column(type: Types::BOOLEAN, options: ['default' => false])]
    #[Groups(['secret_link:read', 'secret_link:created'])]
    private bool $requireAuth = false;

    #[ORM\Column(type: Types::BOOLEAN, options: ['default' => false])]
    private bool $consumed = false;

    #[ORM\Column(type: Types::DATETIME_IMMUTABLE)]
    #[Groups(['secret_link:read', 'secret_link:created'])]
    private \DateTimeImmutable $createdAt;

    #[ORM\Column(type: Types::DATETIME_IMMUTABLE)]
    #[Groups(['secret_link:read', 'secret_link:created'])]
    private \DateTimeImmutable $expiresAt;

    public function getId(): ?Uuid
    {
        return $this->id;
    }

    public function getOwner(): User
    {
        return $this->owner;
    }

    public function setOwner(User $owner): static
    {
        $this->owner = $owner;

        return $this;
    }

    public function getCiphertext(): string
    {
        return $this->ciphertext;
    }

    public function setCiphertext(string $ciphertext): static
    {
        $this->ciphertext = $ciphertext;

        return $this;
    }

    public function isRequireConfirmation(): bool
    {
        return $this->requireConfirmation;
    }

    public function setRequireConfirmation(bool $requireConfirmation): static
    {
        $this->requireConfirmation = $requireConfirmation;

        return $this;
    }

    public function isRequireAuth(): bool
    {
        return $this->requireAuth;
    }

    public function setRequireAuth(bool $requireAuth): static
    {
        $this->requireAuth = $requireAuth;

        return $this;
    }

    public function isConsumed(): bool
    {
        return $this->consumed;
    }

    public function markConsumed(): static
    {
        $this->consumed = true;

        return $this;
    }

    public function getCreatedAt(): \DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function getExpiresAt(): \DateTimeImmutable
    {
        return $this->expiresAt;
    }

    public function isExpired(?\DateTimeImmutable $now = null): bool
    {
        $now ??= new \DateTimeImmutable();

        return $this->expiresAt <= $now;
    }

    // -----------------------------------------------------------------------
    // Lifecycle callbacks
    // -----------------------------------------------------------------------

    #[ORM\PrePersist]
    public function onPrePersist(): void
    {
        $now = new \DateTimeImmutable();
        $this->createdAt = $now;
        $this->expiresAt = $now->modify('+' . self::TTL_SECONDS . ' seconds');
    }
}
